name: apple-stock-price
channels:
- default
dependencies:
- openssl
- python
- pip
- setuptools
- wheel
- sqlite
- pip:
  - alembic==1.13.1
  - aniso8601==9.0.1
  - beautifulsoup4==4.12.3
  - blinker==1.7.0
  - certifi==2024.2.2
  - charset-normalizer==3.3.2
  - click==8.1.7
  - cloudpickle==3.0.0
  - contourpy==1.2.0
  - cycler==0.12.1
  - docker==7.0.0
  - entrypoints==0.4
  - Flask==3.0.2
  - fonttools==4.49.0
  - gitdb==4.0.11
  - GitPython==3.1.42
  - graphene==3.3
  - graphql-core==3.2.3
  - graphql-relay==3.2.0
  - gunicorn==21.2.0
  - idna==3.6
  - importlib_metadata==7.0.2
  - itsdangerous==2.1.2
  - Jinja2==3.1.3
  - joblib==1.3.2
  - kiwisolver==1.4.5
  - lxml==4.9.4
  - Mako==1.3.2
  - Markdown==3.5.2
  - MarkupSafe==2.1.5
  - matplotlib==3.8.3
  - mlflow==2.11.1
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.2.1
  - pillow==10.2.0
  - protobuf==4.25.3
  - pyarrow==15.0.1
  - pyparsing==3.1.2
  - python-dateutil==2.9.0.post0
  - pytz==2024.1
  - PyYAML==6.0.1
  - querystring-parser==1.2.4
  - requests==2.31.0
  - requests-futures==1.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.12.0
  - six==1.16.0
  - smmap==5.0.1
  - soupsieve==2.5
  - SQLAlchemy==2.0.28
  - sqlparse==0.4.4
  - threadpoolctl==3.3.0
  - tqdm==4.66.2
  - typing_extensions==4.10.0
  - tzdata==2024.1
  - urllib3==2.2.1
  - Werkzeug==3.0.1
  - yahooquery==2.3.7
  - zipp==3.17.0


